package fr.istic.tpjpa2024_spring.application.service.exception;

/**
 * Exception thrown when an ID is illegally assigned during the creation of an entity.
 * <p>
 * This exception is used to prevent assigning an ID when creating a new entity,
 * as the ID should be generated by the system rather than provided by the user.
 * Assigning an ID during creation can cause data integrity issues.
 *
 */
public class IllegalIdOnCreateException extends RuntimeException{

    /**
     * Creates a new instance of the exception with a specific message.
     *
     * @param message the message describing the error
     */
    public IllegalIdOnCreateException(String message) {
        super(message);
    }
}
