version: "3.8"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./volumes/postgres-data/backup.sql:/docker-entrypoint-initdb.d/keycloak_dump.sql
        #sudo docker exec -t *id* pg_dump -U keycloak keycloak > ./volumes/postgres-data/backup.sql
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    restart: unless-stopped
    volumes:
        - ./volumes/keycloak-data/realm-export.json:/opt/keycloak/data/import/realm.json:ro

    environment:
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_METRICS_ENABLED: true
      KC_REALM_NAME: "KahootRealm"
      KC_BOOTSTRAP_ADMIN_USERNAME:  admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin_password

    ports:
      - "8180:8080"
    depends_on:
      - postgres
    command:
      - "start-dev"
      - "--import-realm"
